weights: yolov5l6.pt
cfg: ''
data: /kaggle/working/reef.yaml
hyp: /kaggle/input/yolov5pip/yolov5-pip/yolov5/data/hyps/hyp.finetune.yaml
epochs: 300
batch_size: 7
imgsz: 1280
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: cuda:0
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 0
project: reef_enhanced_1280
name: train_yolov5l6_1
exist_ok: true
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 10
freeze: 0
save_period: 8
local_rank: -1
mmdet_tags: false
entity: null
bbox_interval: -1
artifact_alias: latest
neptune_token: null
neptune_project: null
s3_upload_dir: null
upload_dataset: false
save_dir: reef_enhanced_1280/train_yolov5l6_1
