weights: /kaggle/working/yolov5s6
cfg: /kaggle/working/yolov5s6.yaml
data: /kaggle/working/reef.yaml
hyp: /kaggle/working/hyp.yaml
epochs: 40
batch_size: 22
imgsz: 1280
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: cuda:0
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 2
project: reef_enhanced_1280
name: train_yolov5s6_1
exist_ok: true
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 3
freeze:
- 0
save_period: 8
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: reef_enhanced_1280/train_yolov5s6_1
