weights: /kaggle/working/yolov5l6_t5.pt
cfg: ''
data: /kaggle/working/reef.yaml
hyp: /kaggle/working/hyp.yaml
epochs: 6
batch_size: 2
imgsz: 2048
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: false
bucket: ''
cache: null
image_weights: false
device: cuda:0
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 0
project: reef_enhanced_1280
name: train_unenhanced_yolov5l6_5t
exist_ok: true
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 5
freeze: 0
save_period: 3
local_rank: -1
mmdet_tags: false
entity: null
bbox_interval: -1
artifact_alias: latest
neptune_token: null
neptune_project: null
s3_upload_dir: null
upload_dataset: false
save_dir: reef_enhanced_1280/train_unenhanced_yolov5l6_5t
