weights: yolov5l.pt
cfg: ''
data: ./reef.yaml
hyp: /opt/conda/lib/python3.7/site-packages/yolov5/data/hyps/hyp.finetune.yaml
epochs: 20
batch_size: 8
imgsz: 1024
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: cuda:0
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 0
project: YOLOv5
name: run_1280_yolov5l
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
mmdet_tags: false
entity: null
bbox_interval: -1
artifact_alias: latest
neptune_token: ''
neptune_project: ''
s3_upload_dir: ''
upload_dataset: false
save_dir: YOLOv5/run_1280_yolov5l
